[package]
name = "day20"
version = "0.1.0"
authors = ["gremenne <Gregory.Mennenga@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.20"
strum_macros = "0.20"
regex = "1"
lazy_static = "1.4.0"